const {
    Canvas,
    resolveImage
} = require("canvas-constructor");

const {
    registerFont
} = require("canvas");

registerFont(__dirname + "/../../assets/times.ttf", {
    family: "Times New Roman",
});

module.exports = {
    generate: function (demotive, img) {
        return new Promise(async (res, rej) => {
            img = await resolveImage(img);
            const meme = await resolveImage(__dirname + "/../../assets/demotivator.png");
            const canvas = new Canvas(714, 745);
            const size = canvas
                .setTextFont("40px Times New Roman")
                .setTextAlign("center")
                .measureText(demotive[1]);
            const size2 = canvas
                .setTextFont("26px Times New Roman")
                .setTextAlign("center")
                .measureText(demotive[2]);
            const newSize = size.width < 745 ? 40 : (745 / size.width) * 40;
            const newSize2 = size2.width < 745 ? 26 : (745 / size2.width) * 26;
            const buffer = canvas
                .printImage(meme, 0, 0)
                .setTextAlign("center")
                .setColor("#FFFFFF")
                .setTextFont(`${newSize}px Times New Roman`)
                .printWrappedText(demotive[1], 358, 660, 741)
                .setTextFont(`${newSize2}px Times New Roman`)
                .printWrappedText(demotive[2], 358, 660 + newSize, 741)
                .setTextFont(`16px Arial`)
                .setTextAlign("left")
                .setColor("#212121")
                .printText('Generated by Useless', 20, 740)
                .printRoundedImage(img, 46, 46, 622, 551, 0)
                .toBuffer();
            res(buffer);
        });
    }
}