const {
    Canvas,
    resolveImage
} = require("canvas-constructor");

const {
    registerFont
} = require("canvas");

registerFont(__dirname + "/../../assets/arial.ttf", {
    family: "Arial",
});

module.exports = {
    generate: function (floorIs, avatar) {
        return new Promise(async (res, rej) => {
            avatar = await resolveImage(avatar);
            const meme = await resolveImage(__dirname + "/../../assets/floor.png");
            const canvas = new Canvas(622, 407);
            const buffer = canvas
                .printImage(meme, 0, 0)
                .setTextFont("21px Arial")
                .setTextAlign("left")
                .setColor("#000000")
                .printWrappedText('The floor is ' + floorIs, 15, 30, 590)
                .setTextFont("14px Arial")
                .setColor("#616161")
                .printText('Generated by Useless', 20, 403)
                .printRoundedImage(avatar, 140, 88, 24, 24, 0)
                .printRoundedImage(avatar, 440, 85, 50, 50, 0)
                .toBuffer();
            res(buffer);
        });
    }
}